package MedicamentoApp;

/**
* MedicamentoApp/MedicamentoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from medicamentoApp.idl
* lunes 20 de mayo de 2019 03:50:34 PM COT
*/

public final class MedicamentoHolder implements org.omg.CORBA.portable.Streamable
{
  public MedicamentoApp.Medicamento value = null;

  public MedicamentoHolder ()
  {
  }

  public MedicamentoHolder (MedicamentoApp.Medicamento initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MedicamentoApp.MedicamentoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MedicamentoApp.MedicamentoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MedicamentoApp.MedicamentoHelper.type ();
  }

}
