package MedicamentoApp;


/**
* MedicamentoApp/MedicamentoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from medicamentoApp.idl
* lunes 20 de mayo de 2019 03:50:34 PM COT
*/

public abstract class MedicamentoPOA extends org.omg.PortableServer.Servant
 implements MedicamentoApp.MedicamentoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarMedicamento", new java.lang.Integer (0));
    _methods.put ("consultarMedicamento", new java.lang.Integer (1));
    _methods.put ("actualizarMedicamento", new java.lang.Integer (2));
    _methods.put ("eliminarMedicamento", new java.lang.Integer (3));
    _methods.put ("listarMedicamento", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MedicamentoApp/Medicamento/insertarMedicamento
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         String laboratorio = in.read_wstring ();
         String descripcion = in.read_wstring ();
         String composicion = in.read_wstring ();
         String medicamento = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarMedicamento (id, nombre, laboratorio, descripcion, composicion, medicamento);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // MedicamentoApp/Medicamento/consultarMedicamento
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarMedicamento (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // MedicamentoApp/Medicamento/actualizarMedicamento
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         String laboratorio = in.read_wstring ();
         String descripcion = in.read_wstring ();
         String composicion = in.read_wstring ();
         String medicamento = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarMedicamento (id, nombre, laboratorio, descripcion, composicion, medicamento);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // MedicamentoApp/Medicamento/eliminarMedicamento
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarMedicamento (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // MedicamentoApp/Medicamento/listarMedicamento
       {
         String $result = null;
         $result = this.listarMedicamento ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // MedicamentoApp/Medicamento/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MedicamentoApp/Medicamento:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Medicamento _this() 
  {
    return MedicamentoHelper.narrow(
    super._this_object());
  }

  public Medicamento _this(org.omg.CORBA.ORB orb) 
  {
    return MedicamentoHelper.narrow(
    super._this_object(orb));
  }


} // class MedicamentoPOA
