package MedicamentoApp;


/**
* MedicamentoApp/Medicamento.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from medicamentoApp.idl
* lunes 20 de mayo de 2019 03:50:34 PM COT
*/

public interface Medicamento extends MedicamentoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Medicamento
