package MedicamentoApp;


/**
* MedicamentoApp/MedicamentoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from medicamentoApp.idl
* lunes 20 de mayo de 2019 03:50:34 PM COT
*/

public interface MedicamentoOperations 
{
  boolean insertarMedicamento (int id, String nombre, String laboratorio, String descripcion, String composicion, String medicamento);
  String consultarMedicamento (int id);
  boolean actualizarMedicamento (int id, String nombre, String laboratorio, String descripcion, String composicion, String medicamento);
  boolean eliminarMedicamento (int id);
  String listarMedicamento ();
  void shutdown ();
} // interface MedicamentoOperations
