package formula_medicamentoApp;


/**
* formula_medicamentoApp/Formula_MedicamentoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from formula_medicamentoApp.idl
* lunes 20 de mayo de 2019 03:49:12 PM COT
*/

public interface Formula_MedicamentoOperations 
{
  boolean insertarFormula_Medicamento (int id, int id_formula, String cantidad, int id_medicamento);
  String consultarFormula_Medicamento (int id);
  boolean actualizarFormula_Medicamento (int id, int id_formula, String cantidad, int id_medicamento);
  boolean eliminarFormula_Medicamento (int id);
  String listarFormula_Medicamento ();
  void shutdown ();
} // interface Formula_MedicamentoOperations
