package formula_medicamentoApp;


/**
* formula_medicamentoApp/Formula_Medicamento.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from formula_medicamentoApp.idl
* lunes 20 de mayo de 2019 03:49:12 PM COT
*/

public interface Formula_Medicamento extends Formula_MedicamentoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Formula_Medicamento
