package formula_medicamentoApp;


/**
* formula_medicamentoApp/Formula_MedicamentoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from formula_medicamentoApp.idl
* lunes 20 de mayo de 2019 03:49:12 PM COT
*/

public abstract class Formula_MedicamentoPOA extends org.omg.PortableServer.Servant
 implements formula_medicamentoApp.Formula_MedicamentoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarFormula_Medicamento", new java.lang.Integer (0));
    _methods.put ("consultarFormula_Medicamento", new java.lang.Integer (1));
    _methods.put ("actualizarFormula_Medicamento", new java.lang.Integer (2));
    _methods.put ("eliminarFormula_Medicamento", new java.lang.Integer (3));
    _methods.put ("listarFormula_Medicamento", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // formula_medicamentoApp/Formula_Medicamento/insertarFormula_Medicamento
       {
         int id = in.read_long ();
         int id_formula = in.read_long ();
         String cantidad = in.read_wstring ();
         int id_medicamento = in.read_long ();
         boolean $result = false;
         $result = this.insertarFormula_Medicamento (id, id_formula, cantidad, id_medicamento);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // formula_medicamentoApp/Formula_Medicamento/consultarFormula_Medicamento
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarFormula_Medicamento (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // formula_medicamentoApp/Formula_Medicamento/actualizarFormula_Medicamento
       {
         int id = in.read_long ();
         int id_formula = in.read_long ();
         String cantidad = in.read_wstring ();
         int id_medicamento = in.read_long ();
         boolean $result = false;
         $result = this.actualizarFormula_Medicamento (id, id_formula, cantidad, id_medicamento);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // formula_medicamentoApp/Formula_Medicamento/eliminarFormula_Medicamento
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarFormula_Medicamento (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // formula_medicamentoApp/Formula_Medicamento/listarFormula_Medicamento
       {
         String $result = null;
         $result = this.listarFormula_Medicamento ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // formula_medicamentoApp/Formula_Medicamento/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:formula_medicamentoApp/Formula_Medicamento:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Formula_Medicamento _this() 
  {
    return Formula_MedicamentoHelper.narrow(
    super._this_object());
  }

  public Formula_Medicamento _this(org.omg.CORBA.ORB orb) 
  {
    return Formula_MedicamentoHelper.narrow(
    super._this_object(orb));
  }


} // class Formula_MedicamentoPOA
