package formula_medicamentoApp;


/**
* formula_medicamentoApp/Formula_MedicamentoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from formula_medicamentoApp.idl
* lunes 20 de mayo de 2019 03:49:12 PM COT
*/

abstract public class Formula_MedicamentoHelper
{
  private static String  _id = "IDL:formula_medicamentoApp/Formula_Medicamento:1.0";

  public static void insert (org.omg.CORBA.Any a, formula_medicamentoApp.Formula_Medicamento that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static formula_medicamentoApp.Formula_Medicamento extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (formula_medicamentoApp.Formula_MedicamentoHelper.id (), "Formula_Medicamento");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static formula_medicamentoApp.Formula_Medicamento read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Formula_MedicamentoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, formula_medicamentoApp.Formula_Medicamento value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static formula_medicamentoApp.Formula_Medicamento narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof formula_medicamentoApp.Formula_Medicamento)
      return (formula_medicamentoApp.Formula_Medicamento)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      formula_medicamentoApp._Formula_MedicamentoStub stub = new formula_medicamentoApp._Formula_MedicamentoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static formula_medicamentoApp.Formula_Medicamento unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof formula_medicamentoApp.Formula_Medicamento)
      return (formula_medicamentoApp.Formula_Medicamento)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      formula_medicamentoApp._Formula_MedicamentoStub stub = new formula_medicamentoApp._Formula_MedicamentoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
