package DiagnosticoApp;

/**
* DiagnosticoApp/DiagnosticoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from diagnosticoApp.idl
* lunes 20 de mayo de 2019 03:48:05 PM COT
*/

public final class DiagnosticoHolder implements org.omg.CORBA.portable.Streamable
{
  public DiagnosticoApp.Diagnostico value = null;

  public DiagnosticoHolder ()
  {
  }

  public DiagnosticoHolder (DiagnosticoApp.Diagnostico initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DiagnosticoApp.DiagnosticoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DiagnosticoApp.DiagnosticoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DiagnosticoApp.DiagnosticoHelper.type ();
  }

}
