package DiagnosticoApp;


/**
* DiagnosticoApp/Diagnostico.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from diagnosticoApp.idl
* lunes 20 de mayo de 2019 03:48:05 PM COT
*/

public interface Diagnostico extends DiagnosticoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Diagnostico
