/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Diagnostico.DiagnosticoFRAME;
import Formula_Medicamento.FormulaMedicamentoFRAME;
import Formulamedica.FormulaMedicaFRAME;
import Medicamento.MedicamentoFRAME;
import Paciente.PacienteFRAME;

/**
 *
 * @author jpgas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JButton();
        btnMedicamentos = new javax.swing.JButton();
        btnFormulaMedica = new javax.swing.JButton();
        btnFormulaMedicamento = new javax.swing.JButton();
        btnDiagnostico = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENÚ BASE DE DATOS PACIENTES");

        btnPaciente.setForeground(new java.awt.Color(204, 204, 255));
        btnPaciente.setText("1. TABLA PACIENTE");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });

        btnMedicamentos.setForeground(new java.awt.Color(204, 204, 255));
        btnMedicamentos.setText("2. TABLA MEDICAMENTOS");
        btnMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentosActionPerformed(evt);
            }
        });

        btnFormulaMedica.setForeground(new java.awt.Color(204, 204, 255));
        btnFormulaMedica.setText("3. TABLA FORMULA MEDICA");
        btnFormulaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormulaMedicaActionPerformed(evt);
            }
        });

        btnFormulaMedicamento.setForeground(new java.awt.Color(204, 204, 255));
        btnFormulaMedicamento.setText("4. TABLA FORMULA MEDICAMENTO");
        btnFormulaMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormulaMedicamentoActionPerformed(evt);
            }
        });

        btnDiagnostico.setForeground(new java.awt.Color(204, 204, 255));
        btnDiagnostico.setText("5. TABLA DIAGNOSTICO");
        btnDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnPaciente)
                .addGap(49, 49, 49)
                .addComponent(btnMedicamentos)
                .addGap(18, 18, 18)
                .addComponent(btnFormulaMedica))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnFormulaMedicamento)
                .addGap(30, 30, 30)
                .addComponent(btnDiagnostico))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(270, 270, 270))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaciente)
                    .addComponent(btnMedicamentos)
                    .addComponent(btnFormulaMedica))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormulaMedicamento)
                    .addComponent(btnDiagnostico))
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        this.setVisible(false);
        new PacienteFRAME().setVisible(true);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentosActionPerformed
        this.setVisible(false);
        new MedicamentoFRAME().setVisible(true);
    }//GEN-LAST:event_btnMedicamentosActionPerformed

    private void btnDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticoActionPerformed
        this.setVisible(false);
        new DiagnosticoFRAME().setVisible(true);
    }//GEN-LAST:event_btnDiagnosticoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFormulaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormulaMedicaActionPerformed
        this.setVisible(false);
        new FormulaMedicaFRAME().setVisible(true);
    }//GEN-LAST:event_btnFormulaMedicaActionPerformed

    private void btnFormulaMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormulaMedicamentoActionPerformed
        this.setVisible(false);
        new FormulaMedicamentoFRAME().setVisible(true);
    }//GEN-LAST:event_btnFormulaMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagnostico;
    private javax.swing.JButton btnFormulaMedica;
    private javax.swing.JButton btnFormulaMedicamento;
    private javax.swing.JButton btnMedicamentos;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
