package formulamedicaApp;


/**
* formulamedicaApp/FormulamedicaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from formulamedicaApp.idl
* lunes 20 de mayo de 2019 03:50:01 PM COT
*/

public abstract class FormulamedicaPOA extends org.omg.PortableServer.Servant
 implements formulamedicaApp.FormulamedicaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarFormulamedica", new java.lang.Integer (0));
    _methods.put ("consultarFormulamedica", new java.lang.Integer (1));
    _methods.put ("actualizarFormulamedica", new java.lang.Integer (2));
    _methods.put ("eliminarFormulamedica", new java.lang.Integer (3));
    _methods.put ("listarFormulamedica", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // formulamedicaApp/Formulamedica/insertarFormulamedica
       {
         int id = in.read_long ();
         String fecha = in.read_wstring ();
         String dosis = in.read_wstring ();
         int id_paciente = in.read_long ();
         boolean $result = false;
         $result = this.insertarFormulamedica (id, fecha, dosis, id_paciente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // formulamedicaApp/Formulamedica/consultarFormulamedica
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarFormulamedica (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // formulamedicaApp/Formulamedica/actualizarFormulamedica
       {
         int id = in.read_long ();
         String fecha = in.read_wstring ();
         String dosis = in.read_wstring ();
         int id_paciente = in.read_long ();
         boolean $result = false;
         $result = this.actualizarFormulamedica (id, fecha, dosis, id_paciente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // formulamedicaApp/Formulamedica/eliminarFormulamedica
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarFormulamedica (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // formulamedicaApp/Formulamedica/listarFormulamedica
       {
         String $result = null;
         $result = this.listarFormulamedica ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // formulamedicaApp/Formulamedica/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:formulamedicaApp/Formulamedica:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Formulamedica _this() 
  {
    return FormulamedicaHelper.narrow(
    super._this_object());
  }

  public Formulamedica _this(org.omg.CORBA.ORB orb) 
  {
    return FormulamedicaHelper.narrow(
    super._this_object(orb));
  }


} // class FormulamedicaPOA
