package formulamedicaApp;


/**
* formulamedicaApp/Formulamedica.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from formulamedicaApp.idl
* lunes 20 de mayo de 2019 03:50:01 PM COT
*/

public interface Formulamedica extends FormulamedicaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Formulamedica
