package formulamedicaApp;


/**
* formulamedicaApp/FormulamedicaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from formulamedicaApp.idl
* lunes 20 de mayo de 2019 03:50:01 PM COT
*/

public interface FormulamedicaOperations 
{
  boolean insertarFormulamedica (int id, String fecha, String dosis, int id_paciente);
  String consultarFormulamedica (int id);
  boolean actualizarFormulamedica (int id, String fecha, String dosis, int id_paciente);
  boolean eliminarFormulamedica (int id);
  String listarFormulamedica ();
  void shutdown ();
} // interface FormulamedicaOperations
