package formulamedicaApp;

/**
* formulamedicaApp/FormulamedicaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from formulamedicaApp.idl
* lunes 20 de mayo de 2019 03:50:01 PM COT
*/

public final class FormulamedicaHolder implements org.omg.CORBA.portable.Streamable
{
  public formulamedicaApp.Formulamedica value = null;

  public FormulamedicaHolder ()
  {
  }

  public FormulamedicaHolder (formulamedicaApp.Formulamedica initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = formulamedicaApp.FormulamedicaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    formulamedicaApp.FormulamedicaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return formulamedicaApp.FormulamedicaHelper.type ();
  }

}
