package PacienteApp;


/**
* PacienteApp/Paciente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pacienteApp.idl
* lunes 20 de mayo de 2019 03:51:39 PM COT
*/

public interface Paciente extends PacienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Paciente
