package PacienteApp;

/**
* PacienteApp/PacienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pacienteApp.idl
* lunes 20 de mayo de 2019 03:51:39 PM COT
*/

public final class PacienteHolder implements org.omg.CORBA.portable.Streamable
{
  public PacienteApp.Paciente value = null;

  public PacienteHolder ()
  {
  }

  public PacienteHolder (PacienteApp.Paciente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PacienteApp.PacienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PacienteApp.PacienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PacienteApp.PacienteHelper.type ();
  }

}
