package PacienteApp;


/**
* PacienteApp/PacienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pacienteApp.idl
* lunes 20 de mayo de 2019 03:51:39 PM COT
*/

public interface PacienteOperations 
{
  boolean insertarPaciente (int id, String nombre, String apellido, String identificacion, String telefono, String direccion);
  String consultarPaciente (int id);
  boolean actualizarPaciente (int id, String nombre, String apellido, String identificacion, String telefono, String direccion);
  boolean eliminarPaciente (int id);
  String listarPaciente ();
  void shutdown ();
} // interface PacienteOperations
